#!/usr/bin/env python3
"""Startup script for the Integrated Educational Management System.

Launches all four servers:
  - Integration Server (port 5000)
  - College A (SQL Server, port 5001)
  - College B (Oracle, port 5002)
  - College C (MySQL, port 5003)

Database containers are managed via docker-compose.
"""

import os
import sys
import time
import threading
import subprocess

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)


def run_docker_compose(*args):
    """Run a docker compose command in the project directory."""
    compose_file = os.path.join(BASE_DIR, 'docker-compose.yml')
    cmd = ['docker', 'compose', '-f', compose_file] + list(args)
    return subprocess.run(cmd, capture_output=True, text=True)


def check_docker_running():
    """Check if Docker daemon is running."""
    try:
        result = subprocess.run(
            ['docker', 'info'], capture_output=True, text=True, timeout=10)
        return result.returncode == 0
    except Exception:
        return False


def check_containers_healthy():
    """Check if all three database containers are healthy."""
    try:
        result = subprocess.run(
            ['docker', 'ps', '--filter', 'name=college_',
             '--format', '{{.Names}}: {{.Status}}'],
            capture_output=True, text=True, timeout=10)
        output = result.stdout
        containers = ['college_a_sqlserver', 'college_b_oracle',
                       'college_c_mysql']
        healthy = all(
            any(c in line and ('healthy' in line.lower() or 'up' in line.lower())
                for line in output.split('\n'))
            for c in containers
        )
        return healthy, output
    except Exception:
        return False, ''


def start_databases():
    """Start database containers and wait for them to be healthy."""
    print('=' * 60)
    print('  集成教务管理系统 — 启动中...')
    print('  基于XML数据集成技术 — 异构数据库版')
    print('=' * 60)
    print()
    print('[数据库] 检查 Docker 环境...')

    if not check_docker_running():
        print('[错误] Docker 未运行，请先启动 Docker Desktop')
        print('       下载地址: https://www.docker.com/products/docker-desktop')
        sys.exit(1)

    healthy, status = check_containers_healthy()
    if healthy:
        print('[数据库] 所有数据库容器已就绪 ✓')
        print(status)
        return

    print('[数据库] 正在启动数据库容器 (docker-compose up -d)...')
    print('[数据库] 首次启动需要下载镜像，可能需要 5-10 分钟\n')

    result = run_docker_compose('up', '-d')
    if result.returncode != 0:
        print(f'[错误] 启动容器失败:\n{result.stderr}')
        sys.exit(1)
    print(result.stdout)

    # Wait for all databases to be healthy
    print('[数据库] 等待数据库就绪...')
    max_wait = 180  # max 3 minutes
    waited = 0
    while waited < max_wait:
        healthy, status = check_containers_healthy()
        if healthy:
            print(f'[数据库] 所有数据库已就绪 (等待 {waited}秒) ✓')
            print(status)
            return
        time.sleep(5)
        waited += 5
        if waited % 30 == 0:
            print(f'[数据库] 仍在等待... ({waited}秒)')
            _hint = status.strip() or '(无法获取状态)'
            print(f'          {_hint}')

    print('[错误] 数据库启动超时，请手动检查:')
    print('       docker-compose ps')
    print('       docker-compose logs')
    sys.exit(1)


def check_data_exists():
    """Check if test data has been generated by querying each DB."""
    try:
        from college.db import get_engine

        # Just try a quick connection to each DB
        for col_name in ['A', 'B', 'C']:
            import json
            config_path = os.path.join(
                BASE_DIR, 'college', 'configs',
                f'college_{col_name.lower()}.json')
            with open(config_path, encoding='utf-8') as f:
                config = json.load(f)

            engine = get_engine(config)
            with engine.connect() as conn:
                from sqlalchemy import text
                stn = config['tables']['student']['name']
                result = conn.execute(
                    text(f'SELECT COUNT(*) FROM "{stn}"'))
                count = result.fetchone()[0]
                if count == 0:
                    return False
        return True
    except Exception as e:
        # probably tables don't exist yet
        return False


def run_college(config_path, port):
    """Run a college Flask app."""
    from college.app import create_college_app
    app = create_college_app(config_path)
    print(f'[{config_path.split("_")[-1].replace(".json","").upper()}] '
          f'启动于 http://127.0.0.1:{port}')
    app.run(host='127.0.0.1', port=port, debug=False, use_reloader=False)


def run_integration():
    """Run the integration server."""
    from integration.app import app
    print(f'[集成服务器] 启动于 http://127.0.0.1:5000')
    app.run(host='127.0.0.1', port=5000, debug=False, use_reloader=False)


def main():
    """Start all servers."""
    # 1. Ensure databases are up
    start_databases()

    # 2. Generate test data if needed
    if not check_data_exists():
        print()
        print('[系统] 首次运行，正在生成测试数据...')
        print('[系统] 学院A → SQL Server  |  学院B → Oracle  |  学院C → MySQL')
        print()
        from college.data_generator import generate_college_data
        generate_college_data()
        print()
    else:
        print()
        print('[系统] 数据库已有数据，跳过数据生成')
        print()

    # 3. Start Flask servers
    configs = [
        (os.path.join(BASE_DIR, 'college', 'configs', 'college_a.json'), 5001),
        (os.path.join(BASE_DIR, 'college', 'configs', 'college_b.json'), 5002),
        (os.path.join(BASE_DIR, 'college', 'configs', 'college_c.json'), 5003),
    ]

    threads = []
    for config_path, port in configs:
        t = threading.Thread(
            target=run_college, args=(config_path, port), daemon=True)
        t.start()
        threads.append(t)

    # 4. Run integration server in main thread
    run_integration()


if __name__ == '__main__':
    main()
